# Generated by Django 5.0.6 on 2024-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleFiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActionsId', models.CharField(max_length=250)),
                ('Action', models.CharField(max_length=250)),
                ('ExtraParameters', models.CharField(max_length=250)),
                ('Filter', models.CharField(max_length=250)),
                ('BalanceId', models.CharField(max_length=250)),
                ('BalanceType', models.CharField(max_length=250)),
                ('Categories', models.CharField(max_length=250)),
                ('DestinationIds', models.CharField(max_length=250)),
                ('RatingSubject', models.CharField(max_length=250)),
                ('SharedGroup', models.CharField(max_length=250)),
                ('ExpiryTime', models.CharField(max_length=250)),
                ('TimingIds', models.CharField(max_length=250)),
                ('Units', models.IntegerField()),
                ('BalanceWeight', models.IntegerField()),
                ('BalanceBlocker', models.BooleanField()),
                ('BalanceDisabled', models.BooleanField()),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('ID', models.CharField(max_length=250)),
                ('Context', models.CharField(max_length=250)),
                ('FilterIDs', models.CharField(max_length=250)),
                ('ActivationInterval', models.CharField(max_length=250)),
                ('AttributeFilterIDs', models.CharField(max_length=250)),
                ('Path', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Value', models.CharField(max_length=250)),
                ('Blocker', models.BooleanField()),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=250)),
                ('ConnectFee', models.FloatField()),
                ('Rate', models.FloatField()),
                ('RateUnit', models.CharField(max_length=250)),
                ('RateIncrement', models.CharField(max_length=250)),
                ('GroupIntervalStart', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RatingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=250)),
                ('DestinationRatesId', models.CharField(max_length=250)),
                ('TimingTag', models.CharField(max_length=250)),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('ID', models.CharField(max_length=250)),
                ('FilterIDs', models.CharField(max_length=250)),
                ('ActivationInterval', models.DateField()),
                ('Sorting', models.CharField(max_length=250)),
                ('SortingParameters', models.CharField(max_length=250)),
                ('RouteID', models.CharField(max_length=250)),
                ('RouteFilterIDs', models.CharField(max_length=250)),
                ('RouteAccountIDs', models.CharField(max_length=250)),
                ('RouteRatingPlanIDs', models.CharField(max_length=250)),
                ('RouteResourceIDs', models.CharField(max_length=250)),
                ('RouteStatIDs', models.CharField(max_length=250)),
                ('RouteWeight', models.CharField(max_length=250)),
                ('RouteBlocker', models.CharField(max_length=250)),
                ('RouteParameters', models.CharField(max_length=250)),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('Id', models.CharField(max_length=250)),
                ('FilterIDs', models.CharField(max_length=250)),
                ('ActivationInterval', models.DateField()),
                ('QueueLength', models.IntegerField()),
                ('TTL', models.CharField(max_length=250)),
                ('MinItems', models.IntegerField()),
                ('Metrics', models.CharField(max_length=250)),
                ('MetricFilterIDs', models.CharField(max_length=250)),
                ('Stored', models.BooleanField()),
                ('Blocker', models.BooleanField()),
                ('Weight', models.IntegerField()),
                ('ThresholdIDs', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('Id', models.CharField(max_length=250)),
                ('FilterIDs', models.CharField(max_length=250)),
                ('ActivationInterval', models.DateField()),
                ('MaxHits', models.IntegerField()),
                ('MinHits', models.IntegerField()),
                ('MinSleep', models.IntegerField()),
                ('Blocker', models.BooleanField()),
                ('Weight', models.IntegerField()),
                ('ActionIDs', models.CharField(max_length=250)),
                ('Async', models.BooleanField()),
            ],
        ),
    ]
