# Generated by Django 5.0.6 on 2024-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleFiles', '0003_ratingprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='ActivationInterval',
            field=models.CharField(max_length=250),
        ),
    ]
