# Generated by Django 5.0.6 on 2024-05-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleFiles', '0004_alter_routes_activationinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(max_length=250)),
                ('Id', models.CharField(max_length=250)),
                ('FilterIDs', models.CharField(max_length=250)),
                ('ActivationInterval', models.CharField(max_length=250)),
                ('TTL', models.CharField(max_length=250)),
                ('Limit', models.IntegerField()),
                ('AllocationMessage', models.CharField(max_length=250)),
                ('Blocker', models.BooleanField()),
                ('Stored', models.BooleanField()),
                ('Weight', models.IntegerField()),
                ('ThresholdIDs', models.CharField(max_length=250)),
            ],
        ),
    ]
