# Generated by Django 5.0.6 on 2024-05-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleFiles', '0005_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='ActivationInterval',
            field=models.DateField(),
        ),
    ]
