# Generated by Django 5.0.6 on 2024-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_unit', models.CharField(max_length=50)),
                ('rate_increment', models.IntegerField()),
                ('group_interval_start', models.IntegerField()),
            ],
        ),
    ]
